const sidebars = {
  learnSidebar: [
    {
      type: "autogenerated",
      dirName: "learn",
    },
  ],
  useSidebar: [
    {
      type: "autogenerated",
      dirName: "use",
    },
  ],
  buildSidebar: [
    {
      type: "autogenerated",
      dirName: "build",
    },
  ],

  mineSidebar: [
    {
      type: "autogenerated",
      dirName: "mine",
    },
  ],
  stakeSidebar: [
    {
      type: "autogenerated",
      dirName: "stake",
    },
  ],
};

module.exports = sidebars;
